export const actions = {
  quiz: {
    DATA_FETCHING: "QUIZ_DATA_FETCHING",
    DATA_FETCHED: "QUIZ_DATA_FETCHED",
    DATA_FETCH_ERROR: "QUIZ_DATA_FETCH_ERROR",
    QUIZ_DATA_ADDED: "QUIZ_DATA_ADDED",
    QUIZ_DATA_EDITED: "QUIZ_DATA_EDITED",
    QUIZ_DATA_DELETED: "QUIZ_DATA_DELETED",
  },
  question: {
    QUESTION_FETCHED: "QUESTION_FETCHED",
    QUESTION_ADDED: "QUESTION_ADDED",
    QUESTION_EDITED: "QUESTION_EDITED",
    QUESTION_DELETED: "QUESTION_DELETED",
  },
};
